blog-project/website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from .models import db,User
from flask_login import login_user, logout_user, login_required,current_user
from werkzeug.security import generate_password_hash, check_password_hash




auth = Blueprint("auth", __name__)




# user login 

@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully..", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect.', category='error')
                return render_template("login.html"),400
        else:
            flash('Email does not exist.', category='error')
            return render_template("login.html"),404

    return render_template("login.html")






# user registration

@auth.route("/signup", methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get("email")
        username = request.form.get("username")
        password1 = request.form.get("password")
        password2 = request.form.get("repeat_password")
        

        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()

        if email_exists:
            flash('Email is already in use!', category='error')
            return render_template("registration.html"),409
        elif email == "":
            flash("Email shouldn't be empty!", category='error')
            return render_template("registration.html"),204
        elif username_exists:
            flash('Username is already in use!', category='error')
            return render_template("registration.html"),409
        elif password1 != password2:
            flash('Password don\'t match!', category='error')
            return render_template("registration.html"),401
        elif len(username) < 2:
            flash('Username is too short!', category='error')
            return render_template("registration.html"),400
        elif len(password1) <= 6:
            flash('Password is too short!', category='error')
            return render_template("registration.html"),400


        else:
            new_user = User(email=email, username=username, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('User created! Please login to continue')
            return redirect(url_for('auth.login'))

    return render_template("registration.html")





# user logout

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash('logout successfully..',category='success')
    return redirect(url_for("views.home"))



#user email updation

@auth.route("/email", methods=['POST',])
def update_email():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")
        new_email = request.form.get("newEmail")

        user = User.query.filter_by(email=email).first()
        
        old_name=current_user.username
        old_id=current_user.id
        old_pass=current_user.password

        if new_email == "":
            flash("Email shouldn't be empty!", category='error')
            return render_template("dashboard.html"),204
        elif len(new_email) < 11:
            flash('Email is too short!', category='error')
            return render_template("dashboard.html"),400
        else:
            new_user=User(id=old_id,email=new_email,username=old_name,password=old_pass)
            if user:
                if user.email == new_email:
                    flash("Already in use, please enter different email..!", category="error")
                    return redirect(url_for('views.user_dashboard',id=current_user.id,username=current_user.username))
                if check_password_hash(user.password, password):
                    flash("Email updated successfully..", category='success')
                    db.session.merge(new_user)
                    db.session.commit()
                    login_user(new_user, remember=True)
                    return redirect(url_for('views.user_dashboard',id=current_user.id,username=current_user.username))
                else:
                    flash('Password is incorrect.', category='error')
            else:
                flash('Email does not exist.', category='error')

    return redirect(url_for('views.user_dashboard',id=current_user.id,username=current_user.username))





#user username updation

@auth.route("/username", methods=['POST',])
@login_required
def update_username():
    if request.method == 'POST':
        email = request.form.get("userNameEmail")
        password = request.form.get("password_")
       
        new_username = request.form.get("newUser")
        user = User.query.filter_by(email=email).first()

        
        old_id=current_user.id
        old_pass=current_user.password
        
        if new_username == "":
            flash("Username shouldn't be empty!", category='error')
        elif len(new_username) < 3:
            flash('Username is too short!', category='error')
        else:
            new_user=User(id=old_id,email=email,username=new_username,password=old_pass)
            if user:
                if user.username == new_username:
                    flash('Username already exists', category='error')
                    return redirect(url_for('views.user_dashboard',id=current_user.id,username=current_user.username))
                if check_password_hash(user.password, password):
                    flash("username updated successfully..", category='success')
                    db.session.merge(new_user)
                    db.session.commit()
                    login_user(new_user, remember=True)
                    return redirect(url_for('views.user_dashboard',id=current_user.id,username=current_user.username))
                else:
                    flash('Password is incorrect.', category='error')
            else:
                flash('Email does not exist.', category='error')

    return redirect(url_for('views.user_dashboard',id=current_user.id,username=current_user.username))




# user password updation

@auth.route("/password", methods=['POST',])
@login_required
def update_password():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")
        new_password = request.form.get("newPassword")
        confirm_password = request.form.get("repeat_password")

        user = User.query.filter_by(email=email).first()

        old_id=current_user.id
        old_name=current_user.username
        old_email=current_user.email        
        
        new_user=User(id=old_id,email=old_email,username=old_name,
                password=generate_password_hash(
                new_password, method='sha256'))
        
        if user:
            if new_password != confirm_password:
                flash('Password don\'t match!', category='error')
            elif len(new_password) <= 6:
                flash('Password is too short!', category='error')

            elif check_password_hash(user.password, password):
                flash("password updated successfully..", category='success')
                db.session.merge( new_user )
                db.session.commit()
                login_user( new_user, remember=True)
                return redirect(url_for('views.user_dashboard',id=current_user.id,username=current_user.username))
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return redirect(url_for('views.user_dashboard',id=current_user.id,username=current_user.username))

blog-project/website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

  <!-- cdn bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

  <!-- MDB cdn -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css" rel="stylesheet" />


  <!-- template css file -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">


  <!-- favi-icon -->
  <link rel="icon" type="image/x-icon"
    href="https://beckleymechanical.com/wp-content/uploads/2016/11/favicon-300x300.png">

  <title>{% block title %}{% endblock %}</title>

</head>

<body>

  {% with messages = get_flashed_messages(with_categories=True) %}
  {% if messages %}
  {% for category, message in messages %}
  {% if category == "error" %}
  <div class="alert alert-danger alter-dismissible fade show d-flex justify-content-center  message-fade" role="alert"
    id="top-alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissible fade show d-flex justify-content-center  message-fade" role="alert"
    id="top-alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
  {% endif %}

  {% endfor %}
  {% endif %}
  {% endwith %}

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>



  <!-- bootstrap cdn  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

  <!-- cdn of mdb -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js">
  </script>

  <!-- sweetalert -->
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

  <!-- template js file -->
  <script src="{{url_for('static', filename='index.js')}}"></script>


</body>

</html>

blog-project/website/templates/home.html
{% extends "base.html" %}{% block title %}Home{% endblock %}

{% block content%}


<!-- Navbar -->

<nav class="navbar navbar-expand-lg fixed-top bg-light navbar-light">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('views.home') }}" title="blog logo"><img id="blog-logo"
        src="https://www.freeiconspng.com/thumbs/blogger-logo-icon-png/blogger-logo-icon-png-28.png" alt="MDB Logo"
        draggable="false" height="30" /></a>
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Post icon -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto align-items-center">

        <li class="nav-item">
          <a class="nav-link mx-2 btn btn-secondary btn-rounded text-dark" href="{{ url_for('views.home') }}">
            Home
          </a>
        </li>
        <!-- Checking if user is logged in or not -->
        {% if current_user.is_authenticated %}

        <!-- User icon and dropdown -->
        <li class="nav-item me-3 me-lg-0 dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-mdb-toggle="dropdown"
            aria-expanded="false">
            <i class="fas fa-user"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{{ url_for('views.user_dashboard',username=current_user.username,
              id = current_user.id ) }}">My profile</a></li>
            <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
          </ul>
          {% else %}
        <li class="nav-item ms-3">
          <a class="btn btn-black btn-rounded" href="{{ url_for('auth.login') }}">Sign in</a>
        </li>

        {% endif %}

      </ul>
    </div>
  </div>
</nav>

<!-- Category  icon -->
<div class="btn-group">
  <button type="button" class="btn btn-sm btn-primary dropdown-toggle dropdown-toggle-split" data-mdb-toggle="dropdown"
    aria-expanded="false">
    Categories
  </button>
  <ul class="dropdown-menu">
    {% for cat in category %}
    <li>
      <a class="dropdown-item position-relative"
        href="{{ url_for('views.category_post', id=cat.id, category=cat.category)}}">
        {{cat.category}}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>



<!-- Displaying created post in home page -->
<h1 class="text-center pt-2">
  <mark class="rounded-pill shadow-4 border border-secondary">Recent posts</mark>
</h1>
{% if posts %}
{%for post in posts%}
<div class="container mt-4 shadow-4 position-relative">
  <div class="position-relative">
    <span class="small position-absolute top-0 start-0">
      <i class="fas fa-user-circle"></i>
      posted by <strong>{{post.user.username}}</strong>
      <i>{{post.timestamp|timesago}}</i></span>

    {% if post.category.category %}
    <span class="badge bg-dark position-absolute top-0 end-0 ">
      <i class="fa-solid fa-star star"></i>
      {{post.category.category}}</span>
    {% endif %}
  </div>

  <br>

  <h2>{{post.title}}</h2>
  <p>
    {{post.content | trim}}<a href="{{ url_for('views.view_post', id=post.id,slug=post.title) }}">more</a>
  </p>
  <br>


  <span>
    <a class="btn btn-sm btn-primary" href="{{ url_for('views.view_post', id=post.id,slug=post.title) }}">
      view post
    </a>
  </span>

  <hr class="text-primary" />


  <!-- Like view -->

  {% if current_user.is_authenticated %}
  <div title="comments" class="p-2 position-relative">
    <span id="likes-count-{{post.id}}">
      {{ post.likes|length }}</span>
    {% if current_user.id in post.likes|map(attribute="user_id")|list %}
    <i class="fa-solid fa-hands-clapping fa-lg text-primary" id="like-button-{{post.id}}"
      onclick="like({{post.id}})"></i>
    {% else %}
    <i class="fa-solid fa-hands-clapping fa-lg" id="like-button-{{post.id}}" onclick="like({{post.id}})"></i>
    {% endif %}
  </div>

  <div class="position-absolute bottom-0 start-50 translate-middle-x">
    <!--no of comments-->
    <a href="{{ url_for('views.view_post', id=post.id,slug=post.title) }}">
      <i class="fa-regular fa-comment"></i> {{ post.comments | length }}
    </a>
  </div>
  {%else%}
  <div class="position-absolute bottom-0 start-50 translate-middle-x">
    <!--no of comments-->
    <a href="{{ url_for('views.view_post', id=post.id,slug=post.title) }}">
      <i class="fa-regular fa-comment"></i> {{ post.comments | length }}
    </a>
  </div>
  {% endif %}





</div>
{% endfor %}
{%else%}
<h4 class="text-center pt-5"><em>Currently there are no posts available...</em></h4>
{% endif %}



<!-- Copyright -->
{% if posts %}
<footer class="bg-light text-center text-lg-start mt-5 border rounded-top">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-dark" href="{{ url_for('views.home') }}">thinkpad.blog</a>
  </div>
  {% endif %}
</footer {% endblock %}

blog-project/website/templates/login.html
{% extends "base.html" %} {% block title %}login{% endblock %}

{% block content%}

<!-- Login page -->
<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      
      <h1 class="text-center pt-2">
        <mark class="rounded-pill shadow-4 border border-primary bg-light">Login</mark>
      </h1>

      <!-- image -->
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://img.freepik.com/free-vector/mobile-login-concept-illustration_114360-135.jpg?w=2000"
          class="img-fluid" alt="Sample image">
      </div>

      <!-- Form -->
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <form method="POST" name="login">
          <div class="form-outline mb-4">
            <input type="text" id="email" class="form-control form-control-lg" name="email" autocomplete="off" />
            <label class="form-label" for="email">Enter a email address</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-3">
            <input type="password" id="password" class="form-control form-control-lg" name="password" />
            <label class="form-label" for="password">Enter your password</label>
          </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <button type="submit" class="btn btn-primary btn-lg"
              style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{{ url_for('auth.sign_up') }}"
                class="link-danger">Register</a></p>
          </div>

        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

blog-project/website/templates/posts.html
{% extends "base.html" %} {% block title %}Create post{% endblock %}

{% block content %}

<nav aria-label="breadcrumb" class="pb-4">
  <ol class="breadcrumb fs-6">
    <li class="breadcrumb-item lead"><a
        href="{{ url_for('views.user_dashboard', id=current_user.id, username=current_user.username) }}">Profile</a>
    </li>
    <li class="breadcrumb-item active lead" aria-current="page">Create post</li>
  </ol>
</nav>

<div class="container">

  <h1 class="text-center pt-2"><span class="badge bg-primary">Create Post</span></h1>


  <!-- Post creation form -->

  <form method="post" name="form" class="pt-4">
    <!-- Title input -->
    <div class="form-outline mb-4">
      <input type="text" name="title" id="form4Example2" class="form-control" />
      <label class="form-label" for="form4Example2">Title</label>
    </div>

    <!-- category input -->

    <div class="mb-4 =">
      <div class="select-div">
        <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="Category">
          <option selected disabled>Select category</option>
          {% for category in categories%}
          <option value="{{category.category}}">{{category.category}}</option>
          {% endfor %}
        </select>
      </div>
    </div>


    <!-- Content input -->
    <div class="form-outline mb-4">
      <textarea class="form-control" name="content" id="form4Example3" rows="4"></textarea>
      <label class="form-label" for="form4Example3">Share your thoughts</label>
    </div>

    <!-- Submit button -->
    <button type="submit" class="btn btn-primary b mb-4">publish</button>
  </form>

</div>




{% endblock %}

blog-project/website/templates/registration.html
{% extends "base.html" %} {% block title %}Registration{% endblock %}

{% block content%}

<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">

      <h1 class="text-center pt-2">
        <mark class="rounded-pill shadow-4 border border-primary bg-light">Register</mark>
      </h1>

      <div class="col-md-9 col-lg-6 col-xl-5">
        <img
          src="https://media.istockphoto.com/vectors/register-account-submit-access-login-password-username-internet-vector-id1281150061?k=20&m=1281150061&s=612x612&w=0&h=wpCvmggedXRECWK-FVL98MMllubyevIrXuUu50fdCqE="
          class="img-fluid" alt="Sample image">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">

        <form method="POST" name='registration'>

          <!-- Email input -->
          <div class="form-outline mb-4">
            <input type="text" id="email" class="form-control form-control-lg" name="email"
              placeholder="gary@vaynermedia.com" autocomplete="off" />
            <label class="form-label" for="email">Enter your email</label>
          </div>
          <!-- username input -->
          <div class="form-outline mb-3">
            <input type="text" id="username" class="form-control form-control-lg" name="username"
              placeholder="Gary Vaynerchuk" autocomplete="off" />
            <label class="form-label" for="username">Enter your username</label>
          </div>

          <!-- Password input -->

          <label id="passwordLable" class="passlabel small" style="display: none;">Type at least 7 and no more than 12
            characters</label>
          <div class="form-outline mb-3">
            <input type="password" id="password" class="form-control form-control-lg" name="password"
              onfocus="labelVisible()" onblur="labelInvisible()" />
            <label class="form-label" for="password">Enter your password</label>
          </div>

          <div class="form-outline mb-3">
            <input type="password" id="repeat_password" class="form-control form-control-lg" name="repeat_password" />
            <label class="form-label" for="repeat_password">Confirm password</label>
          </div>
          <div class="text-center text-lg-start mt-4 pt-2">
            <button type="button" id="register-btn" class="btn btn-primary btn-lg"
              style="padding-left: 2.5rem; padding-right: 2.5rem;" onclick="formValidation()">sign up</button>
          </div>

        </form>



      </div>
    </div>
  </div>
</section>
{% endblock %}

blog-project/website/templates/view_post.html
{% extends "base.html" %}{% block title %}View post{% endblock %}

{% block content%}

{% if post_view %}
{%for post in post_view%}

<nav aria-label="breadcrumb" class="pb-4">
  <ol class="breadcrumb fs-6">
    <li class="breadcrumb-item lead"><a href="{{ url_for('views.home') }}">Home</a></li>
    <li class="breadcrumb-item active lead" aria-current="page">Post</li>
  </ol>
</nav>

<div class="container mt-4 shadow-4 position-relative">


  <h2>{{post.title}}</h2>
  <em>
    {{post.content}}
  </em>


  <span class="small position-absolute top-0 end-0 badge bg-dark ">
    author:
    <i class="fas fa-user-circle ms-2"></i>
    <strong>{{post.user.username}}</strong>
  </span>
</div>
<hr />




<!-- Posted comment -->

{%if mycomment %}
{%for comment in mycomment%}
<div class="card mb-3">
  <div class="card-body">
    <div class="d-flex flex-start">
      {% if comment.user_id %}
      <img class="rounded-circle shadow-1-strong me-3" src="{{url_for('views.view_img',user_id=comment.user_id)}}"
        alt="avatar" width="40" height="40" style="object-fit: cover;"/>
      {%else%}
      <img class="rounded-circle shadow-1-strong me-3"
        src="https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/b8/10/b4/b810b4a7-a0a3-72e5-f2cd-c6a7c56b9e4c/artwork.jpg/1200x1200bf-60.jpg"
        alt="avatar" width="40" height="40" />
      {% endif %}

      <div class="w-100">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h6 class="text-primary fw-bold mb-0">
            {{ comment.guestname }}
            <em class="text-dark ms-2">{{ comment.Comment }}
            </em>
          </h6>
          <p class="mb-0">{{ comment.timestamp |timesago }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endif %}

<!-- Create Comment -->

<!-- Registered user comment -->
<div class="container mt-4 shadow-4">
  {% if current_user.is_authenticated %}
  {%if post%}
  <form action="{{ url_for('views.comments',id=post.id,slug=post.slug) }}" method="post" role="form">
    <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
      <div class="d-flex flex-start w-100">

        <img class="rounded-circle shadow-1-strong me-3" src="{{url_for('views.view_img',user_id=current_user.id)}}"
          alt="avatar" width="40" height="40" style="object-fit: cover;"/>

        <div class="form-outline w-100">
          <textarea class="form-control" id="textAreaExample" rows="4" style="background: #fff;"
            name="comment"></textarea>
          <label class="form-label" for="textAreaExample">Comment</label>
        </div>
      </div>
      {%endif%}
      <div class="float-end mt-2 pt-1">
        <button type="submit" class="btn btn-primary btn-sm">Post comment</button>
      </div>
    </div>
  </form>

  {% else %}
  <!-- Guest user comment -->
  {%if post%}
  <form action="{{ url_for('views.comments',id=post.id,slug=post.slug) }}" method="post" role="form">
    <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
      <div class="form-outline mb-3">
        <input type="text" id="name" class="form-control" name="name" />
        <label class="form-label" for="name">Name</label>
        {%endif%}
      </div>

      <div class="d-flex flex-start w-100">
        <img class="rounded-circle shadow-1-strong me-3"
          src="https://is5-ssl.mzstatic.com/image/thumb/Music115/v4/b8/10/b4/b810b4a7-a0a3-72e5-f2cd-c6a7c56b9e4c/artwork.jpg/1200x1200bf-60.jpg"
          alt="avatar" width="40" height="40" />
        <div class="form-outline w-100">
          <textarea class="form-control" id="textAreaExample" rows="4" style="background: #fff;"
            name="comment"></textarea>
          <label class="form-label" for="textAreaExample">Comment</label>
        </div>
      </div>

      <div class="float-end mt-2 pt-1">
        <button type="submit" class="btn btn-primary btn-sm">Post comment</button>
      </div>
    </div>
  </form>
  {% endif %}

</div>

{%endfor%}
{%endif%}


{% endblock %}